### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by frederikbosch** [genkgo/mail#10]

**Comment by mpyw** [comment]
I introduced on Qiita (SNS for Japanese developers)

[PHP7.1未満お断り！最新PHPメーラーライブラリ Genkgo/Mail を試してみる - Qiita](https://qiita.com/mpyw/items/88161f9a809e063823c6)

**Comment by frederikbosch** [comment]
Many thanks @mpyw! I included it in the README.

**Comment by ragboyjr** [comment]
This library looks amazing, i'd love to try and contribute some documentation. What kind of docs are you thinking? readthedocs? github pages? http://couscous.io? Let me know, and I'll try to get something together.

**Comment by frederikbosch** [comment]
Thanks! I am familiar with readthedocs and github pages. Of those I would prefer readthedocs. Don't know couscous, but it seems pretty nice too.

**Comment by frederikbosch** [comment]
Maybe I should just create a couscous account and add the readme example as a start. Then you and others can join and help to get it to the next level.

**Comment by GawainLynch** [comment]
FWIW @bobdenotter has been setting up Couscous for a number of core extensions in @bolt and we're pretty happy with the results. Ultimately it is probably bigger time saver :smile_cat:

**Comment by bobdenotter** [comment]
Hi all, 

Yes, and i've made some simple modifications to integrate a better menu structure, as well as a simple search using Tipue, that still works on statically generated pages. 

See here for details: 

 - https://github.com/bolt/Extension-docs-template/blob/master/public/default.twig#L99-L107
 - https://github.com/bolt/boltforms/blob/4.1/couscous.yml#L21-L50

If you have questions, don't hesitate to ask!

**Comment by ragboyjr** [comment]
Sounds good, i'll use those as a starting point and go from there. Thanks!

**Comment by k00ni** [comment]
I had some newbie-questions, got an answer and now, i would like to provide some example code and descriptions. But i couldn't find a link to the current working prototype of the documentation. Is there anything there yet?

**Comment by frederikbosch** [comment]
Nope. It's a high priority of mine. Will go for it asap.

**Comment by k00ni** [comment]
Do you prefer a separate repository/service or do you like it in the code, like `doc/foo.md`? Or even as part of the README.md? I would suggest in the code, because it allows versioning of the docs.

**Comment by frederikbosch** [comment]
I'll go for couscous as suggested here. Will let everyone know when it is there.

**Comment by frederikbosch** [comment]
Started with documentation via ReadTheDocs.
