### ISSUE TITLE
Tests for formats and attachments

### ISSUE THREAD

**Issue by Lewiscowles1986** [genkgo/mail#13]
One thing most other mail libraries are really poor at is integrating attachments that are not `text/plain`, `text/html` or one of the `image/*` mime-types like for example ical / vcard.

It'd be really nice to see tests for that. Is it something you feel is outside of library need / support?

**Comment by frederikbosch** [comment]
See https://github.com/genkgo/mail/blob/master/test/Unit/Mime/FileAttachmentTest.php and combine it with the example in the readme. I havent tested vCards, but should be supported out-of-the-box.

**Comment by frederikbosch** [comment]
Please let me know if you find something that it is not working, closing for now.

**Comment by frederikbosch** [comment]
You might also want to have a look at https://github.com/genkgo/mail/blob/master/src/Mime/ResourceAttachment.php fir non-file attachments.
