### ISSUE TITLE
ssl custom context stream options

### ISSUE THREAD

**Issue by rodrigo-garcia-engrande** [genkgo/mail#19]
I do not see a way to add custom context stream options, for example
verify_peer, verify_peer_name and allow_self_signed
Is it possible?

**Comment by frederikbosch** [comment]
At this moment not. But I'd love to have this feature. Since I already foresaw that secure streams require configuration, I created the `SecureConnectionOptions` class. It allows to add your suggestions. Are you able to create a PR for this?

**Comment by rodrigo-garcia-engrande** [comment]
Not know, but as soon as i am able will do. Thanks.

**Comment by frederikbosch** [comment]
Ok, if I find time, I will fix this. Thanks for the suggestion.

**Comment by frederikbosch** [comment]
PR #49 fixes this issue. In order to create a secure connection with extra stream context options, you cannot use the client factory but you will have to setup a connection instance yourself.

```php
$client = new Client(
    new SecureConnection(
        'host',
        465,
        new SecureConnectionOptions(
            STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT,
            10,
            ['verify_peer' => false]
        )
    )
);
