### ISSUE TITLE
How to send a mail using SMTP?

### ISSUE THREAD

**Issue by k00ni** [genkgo/mail#38]
Hi guys, i would like to use your library, but got stock. Would you mind providing a simple example to send a text mail via SMTP (with given port, username and password)?

I scanned your examples and tests and tried https://qiita.com/mpyw/items/88161f9a809e063823c6, but got lost in all the classes. 

Help would be appreciated!

**Comment by frederikbosch** [comment]
The example - which is not text but html - from the frontpage is not sufficient?

**Comment by frederikbosch** [comment]
The same example as the frontpage of frontpage of the library bu then for text only would be as follows.

```php
// import all the used classes.

$message = (new PlainTextMessage('Hello world'))
    ->withHeader(new Subject('Hello World'))
    ->withHeader(From::fromEmailAddress('from@example.com'))
    ->withHeader(To::fromSingleRecipient('to@example.com', 'name'))
    ->withHeader(Cc::fromSingleRecipient('cc@example.com', 'name'));

$transport = new SmtpTransport(
    ClientFactory::fromString('smtp://user:pass@host/')->newClient(),
    EnvelopeFactory::useExtractedHeader()
);

$transport->send($message);

**Comment by k00ni** [comment]
My bad, i confused the `host` information with something like `http://example.com`, but it seems only `example.com`, because of the `smtp` protocol. Will try the example of the frontpage again.

@frederikbosch: thanks for the fast reply!

Gave me a hint:
* https://stackoverflow.com/questions/4738348/is-there-an-accepted-syntax-for-smtp-server-and-how-to-parse-it

**Comment by frederikbosch** [comment]
Regarding the SMTP URI. There are three options.
1. `smtp://`: Uses port 587 by default, connects insecure and upgrades to a secure connection using STARTTLS. Insecure connections are **not** allowed. This default and recommended.
2. `smtps://`: Uses port 465 by default and uses a secure connection directly.
3. `smtps-starttls://`: Uses port 25 by default, tries to upgrade using STARTTLS, but allows insecure connection if the upgrade to a secure connection fails.

**Comment by k00ni** [comment]
**Small hint:** In case the username contains an `@`, you need to replace it with `%40`.

Your scripts work like a charm, after i got them setup. Its a little bit confusing with all the classes, but i get used to it. Thanks.
