### ISSUE TITLE
Support internationalized email addresses (RFC 6530)

### ISSUE THREAD

**Issue by DanMan** [genkgo/mail#57]
Unicode characters are allowed in email addresses. It looks like you do handle Unicode in domains but not in the local part. In any case, it's not mentioned in the README, so here we are. If it is supported (and to what extent), you probably should mention it there.

**Comment by frederikbosch** [comment]
You are right: there is no support yet for unicode local parts. I was not aware of it. I will address this with a PR any time soon.
