### ISSUE TITLE
PHP 8+ support

### ISSUE THREAD

**Issue by dennis-fedco** [genkgo/mail#91]
Hello
On PHP 8.0.3 when I do `composer require genkgo/mail`

I get an error message:

    [InvalidArgumentException]
    Package genkgo/mail has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

Can you please update the package to install on PHP 8.0 systems?

**Comment by frederikbosch** [comment]
See #92, will make sure a new version is tagged today

**Comment by frederikbosch** [comment]
Done, 2.7.16 also supports PHP 8.0

**Comment by dennis-fedco** [comment]
Thank you!
