### ISSUE TITLE
About the encoding of AlternativeText

### ISSUE THREAD

**Issue by riku22** [genkgo/mail#95]
Hello.

Currently, Base64 is specified as the encoding of AlternativeText, but I would like to change it to encode with 8bit.
As a test, I added `withHeader(new ContentTransferEncoding("8bit"))`, but the base64-encoded character string was displayed as it was in the body.
Is there any way?

Best regards.

**Comment by frederikbosch** [comment]
If you are using Chinese characters, it will automatically become base64, not 8bit. What is the text you are inserting?

**Comment by riku22** [comment]
Hello.

Hmm, I see.
I use Japanese for the text.

Best regards.

**Comment by frederikbosch** [comment]
The content transfer encoding for a plain text part [is decided](https://github.com/genkgo/mail/blob/82f6e54dce76aa22702317da7f6f2c999637b8df/src/Mime/PlainTextPart.php#L25) on its content via the [OptimalTransferEncodedTextStream](https://github.com/genkgo/mail/blob/82f6e54dce76aa22702317da7f6f2c999637b8df/src/Stream/OptimalTransferEncodedTextStream.php#L48). If the content does contain any non 7bit character, then the second question is what will generate the smallest size between quoted-printable and base64. I guess with Japanese characters base64 is a more optimal solution than quoted-printable.

The same methodology is used for [html parts](https://github.com/genkgo/mail/blob/82f6e54dce76aa22702317da7f6f2c999637b8df/src/Mime/HtmlPart.php#L29).

**Comment by riku22** [comment]
Hello.

OK, I see.
thank you very much.

Best regards.
